# Generated by Django 2.0.1 on 2018-03-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OcularPDB', '0002_choroidprotein'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitreousProtein',
            fields=[
                ('ens_id', models.CharField(default='x', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('posterior_hyaloid', models.IntegerField()),
                ('anterior_hyaloid', models.IntegerField()),
                ('vitreous_base', models.IntegerField()),
                ('vitreous_core', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='choroidprotein',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
